patch: add data leaks to log threat for non android repos
Privado-Inc/privado-core pull request #113
Opened 2022-09-01 07:15 UTC by abhstabs

Hi @pandurangpatil / @khemrajrathore, 

Made changes on the basis of suggestions in the ticket. Please have a look. 

Thank you.

2022-09-01 07:31 UTC, pandurangpatil commented
@ojaswa1942 Review this pull request, as you have more context

2022-09-01 08:59 UTC, ojaswa1942 requested changes
Also, we need a similar format for `processProcessingViolations` while we are at it.

2022-09-01 08:59 UTC, ojaswa1942 commented on src/main/scala/ai/privado/threatEngine/ThreatEngineExecutor.scala
> +    } else {
@abhstabs Can we handle this better in a generalized way?   
With more such threats, this will clutter with if-else-if-else statements.

2022-09-01 09:27 UTC, ojaswa1942 commented
@abhstabs I happened to make the same changes earlier. Let me commit and push them on another branch, and you can take a call on whatever makes more sense.

2022-09-01 09:29 UTC, ojaswa1942 commented
@abhstabs https://github.com/Privado-Inc/privado-core/commit/f7871172c22ba0db211a6bfb9dffe491b66e1248

2022-09-06 05:53 UTC, abhstabs commented
@ojaswa1942 Updated. Please have a look. Thank you.

2022-09-06 12:00 UTC, ojaswa1942 commented
@abhstabs I don't see any new commits here.

2022-09-06 12:12 UTC, ojaswa1942 approved these changes
:shipit:

2022-09-08 07:04 UTC, pandurangpatil commented
@ojaswa1942 @khemrajrathore is this done and can be merged?

2022-09-08 07:08 UTC, khemrajrathore approved these changes
LGTM

2022-09-08 08:47 UTC, merged