Export the probable sinks to privado.json file
Privado-Inc/privado-core pull request #200
Opened 2022-11-17 07:34 UTC by dbMundada

- Currently we have limited set of rules written for Third Parties & Databases.
- So, after scanning it may be case that some Third Party is present but not detected via tool as rule missing.
- We will be exporting all the external packages in **probableSinks** key in privado.json

2022-11-17 08:42 UTC, pandurangpatil requested changes
handle the requested change.

2022-11-17 08:42 UTC, pandurangpatil commented on src/main/scala/ai/privado/exporter/SinkExporter.scala
> +    var blackListedGroupIds: List[String] = List(
Convert this skiplist into config rule files picked from privado skiplist.yml configuration kept inside `config` folder.

2022-11-17 11:01 UTC, khemrajrathore commented on src/main/scala/ai/privado/exporter/SinkExporter.scala
> +    val taggedSinkMethods = cpg.tag.where(_.nameExact(Constants.catLevelOne).valueExact(CatLevelOne.SINKS.name)).call.l.map(i => i.methodFullName.split(":").head)
Instead of `head` use `headOption.getOrElse`. Head will return error if split return empty

2022-11-17 11:01 UTC, khemrajrathore commented on src/main/scala/ai/privado/exporter/SinkExporter.scala
> +    val dependenciesTPs = cpg.method.external.l.map(i => i.fullName.split(":").head)
Instead of `head` use `headOption.getOrElse`. Head will return error if split return empty

2022-11-17 11:02 UTC, khemrajrathore commented on src/main/scala/ai/privado/exporter/SinkExporter.scala
> +    val taggedSinkMethods = cpg.tag.where(_.nameExact(Constants.catLevelOne).valueExact(CatLevelOne.SINKS.name)).call.l.map(i => i.methodFullName.split(":").head)
Also `dedup` the list to get unique methodFullNames

2022-11-17 11:04 UTC, khemrajrathore commented on src/main/scala/ai/privado/exporter/SinkExporter.scala
> +        (res.length == 0)
we can write this as `blackListedGroupIds.filter(blackListGroup => str.startsWith(blackListGroup)).empty`

2022-11-17 11:05 UTC, khemrajrathore commented on src/main/scala/ai/privado/exporter/SinkExporter.scala
> +      .map((str) => str.split("\\.").take(3).mkString("."))
check if we need exception handling here

2022-11-19 13:25 UTC, khemrajrathore commented on src/main/scala/ai/privado/exporter/SinkExporter.scala
> +    val taggedSinkMethods = cpg.tag.where(_.nameExact(Constants.catLevelOne).valueExact(CatLevelOne.SINKS.name)).call.l.map(i => i.methodFullName.split(":").head)
@dbMundada

2022-11-19 13:25 UTC, khemrajrathore commented on src/main/scala/ai/privado/exporter/SinkExporter.scala
> +    val dependenciesTPs = cpg.method.external.l.map(i => i.fullName.split(":").head)
@dbMundada

2022-11-21 07:13 UTC, pandurangpatil reviewed
Looks good to me @khemrajrathore verify it once and if looks good from your side. Go ahead and merge it.

2022-11-21 07:16 UTC, pandurangpatil approved these changes

2022-11-21 07:48 UTC, khemrajrathore approved these changes
LGTM

2022-11-21 07:49 UTC, merged