Add/member support
Privado-Inc/privado-core pull request #339
Opened 2023-02-13 06:43 UTC by khemrajrathore

2023-02-14 09:28 UTC, pandurangpatil requested changes
@khemrajrathore You have made changes related to default semantics usage. The changes look good to me.  However, let's run this branch through a comparison script in order to make sure there is no diff.

cc: @dbMundada

2023-02-14 09:33 UTC, pandurangpatil requested changes
Make requested change.

2023-02-14 09:33 UTC, pandurangpatil commented on build.sbt
> +  "org.apache.logging.log4j"         % "log4j-api"               % "2.19.0",
@khemrajrathore remove this dependency of `log4j-api`; this one is not required.

2023-02-14 10:36 UTC, khemrajrathore commented
Have removed `log4j-api` dependency

2023-02-15 05:12 UTC, pandurangpatil approved these changes

2023-02-15 05:13 UTC, merged